### ISSUE TITLE
Media query combiner produces invalid css

### ISSUE THREAD

**Issue by Ramblurr** [thheller/shadow-css#22]
#### Description

I have some aliases like this:

```clojure
:dark                            "@media (prefers-color-scheme: dark)"
:hover-mouse                     "@media(hover: hover) and (pointer: fine)"
```
(these are media queries for targeting hover states on non-touch devices. [more info](https://www.smashingmagazine.com/2022/03/guide-hover-pointer-media-queries/)

With hiccup like this:
```clojure
[:dark [:hover-mouse [:hover :bg-white]]]
```
shadow-css produces css like this, which has mismatching parens:

```css
@media (prefers-color-scheme: dark) and hover: hover) and (pointer: fine){
  .fairy_box_web_views_home__L361_C16:hover {
    background-color: #fff;
  }
}
```

#### Relevant shadow-css code:
https://github.com/thheller/shadow-css/blob/b3c97fe3caf16fab1a90fb93a7baad76fe15aa46/src/main/shadow/css/analyzer.cljc#L106-L112
