### ISSUE TITLE
@starting-style CSS at-rule support

### ISSUE THREAD

**Issue by robinlahtinen** [thheller/shadow-css#28]
Currently `shadow-css` doesn't support the `@starting-style` CSS at-rule.

Documentation: [https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style](https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style)

### Proposal
Add support for the rule. `@starting-style` should be inside the generated CSS class.

```clojure
(css ["@starting-style" {:opacity   "0"
                         :transform "scaleX(1)"}])
```

Compiles to:

```css
.my_app__L5C16 {
    @starting-style {
        opacity: 0;
        transform: scaleX(1);
    }
}
```

**Comment by thheller** [comment]
Never heard of `@starting-style` before.

There currently is some special case handling for `@media` selectors and it seems like this could be generalized to cover this. Are there more things like this? I haven't really kept up with the CSS developments for a while now.

**Comment by thheller** [comment]
Went oder the docs and seems like `@starting-style` is just a regular [block at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule#block_at-rules). What confused me was that it is valid inside another selector, which other `@` blocks do not seem to be.

Regardless, it seems that

```css
@starting-style {
  .my_app__L5C16 {
    opacity: 0;
    transform: scaleX(1);
  }
}
```

is just was valid and could be generated by slightly modifying how `@media` is handled currently.
